baseURL = 'https://felipesilveira.com.br/'
languageCode = 'pt-br'
theme = "hugo-theme-hello-4s3ti"
title = 'CadÃª o Log ?'
copyright = "All Rights Reserved"
IsMultiLingual = false
defaultContentLanguage = 'pt-br'
publishDir = "docs"
[params]
  defaultTheme = "dark"
  EnableThemeToggle = true
  EnableSharingButtons = true
  EnableGlobalLanguageMenu = true
  backgroundImage = "static/coolapso.webp"
  backgroundEffects = true
  showPosts = true
  paginate = 5
  tags = false
  ReadMoreText = true
  fontAwesome = { KitURL = "https://kit.fontawesome.com/0ed5cec925.js" }
  ShowReadingTime = true
  LastModDisplay = true
  logo = { logoText = "felipesilveira.com.br", logoCursorColor = "#ffffff" }
  footer = { showVersion = false, socialIcons = true, author = true, rss = false, trademark = false, copyright = false, bottomText = [""] }

[params.author]
name = "Felipe Silveira"

[[params.social]]
  name = "github"
  url = "https://github.com/felipe8398"

[[params.social]]
  name = "website"
  url = "https://felipesilveira.com.br"
  icon = "fa-solid fa-terminal"

#[[params.social]]
#  name = "youtube"
#  url = "https://youtube.com/cadeolog"

[[params.social]]
  name = "x-twitter"
  url = "https://x.com/cadeolog"

[[params.social]]
  name = "instagram"
  url = "https://www.instagram.com/felip3.png/"

#[[params.social]]
#  name = "twitch"
#  url = "https://twitch.tv/cool4pso"

#[[params.social]]
#  name = "Buy me a coffee"
#  url = "https://www.buymeacoffee.com/coolapso"
#  icon = "fa-solid fa-coffee"

[languages]
  [languages.pt-br]
    weight = 1
    languageName = "Portugues"

#  [languages.en]
#    weight = 2
#    params = { backgroundImage = "../static/coolapso.webp" }

#    [[languages.en.menu.main]]
#      identifier = "posts"
#      name = "Posts"
#      url = "/posts"
#      weight = 1

#    [[languages.en.menu.main]]
#      identifier = "about"
#      name = "About"
#      url = "#"
#      weight = 2

#    [[languages.en.menu.main]]
#      identifier = "projects"
#      name = "Projects"
#      url = "/projects"

#    [[languages.en.menu.main]]
#      identifier = "Project 1"
#      name = "Project 1"
#      url = "#"
#      parent = "projects"

#    [[languages.en.menu.main]]
#      identifier = "tools"
#      name = "Tools"

#    [[languages.en.menu.main]]
#      identifier = "tool1"
#      name = "tool1"
#      url = "#"
#      parent = "tools"

#    [[languages.en.menu.main]]
#      identifier = "Tool2"
#      name = "tool2"
#      url = '#'
#      parent = "tools"

[taxonomies]
  tag = "tags"
  category = "blog"

[menu]
   [[menu.main]]
    identifier = "sobre"
    name = "Sobre"
    url = "/sobre"
    weight = 1

  [[menu.main]]
    identifier = "posts cloud"
    name = "Cloud"
    url = "/cloud"
    weight = 2

  [[menu.main]]
    identifier = "posts red"
    name = "RedTeam"
    url = "/red"
    weight = 3

  [[menu.main]]
    identifier = "posts blue"
    name = "BlueTeam"
    url = "/blue"
    weight = 4


  [[menu.main]]
    identifier = "curriculo"
    name = "Curriculo"
    url = "/cv"
    weight = 5
#  [[menu.main]]
#    identifier = "Projeto 1"
#    name = "Projeto 1"
#    url = "#"
#    parent = "projects"

#  [[menu.main]]
#    identifier = "ferramenta 1"
#    name = "Ferramenta 1"
#    url = "#"
#    parent = "tools"

#  [[menu.main]]
#    identifier = "Ferramenta 2"
#    name = "Ferramenta 2"
#    parent = "tools"
#    url = "#"

#  [[menu.main]]
#    identifier = "Ferramenta 3"
#    name = "Ferramenta 3"
#    parent = "tools"
#    url = "#"

